apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    team: platform
spec:
  project: default

  source:
    repoURL: https://github.com/JustFiesta/microservices-demo.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
      - values.yaml
      - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true        # Remove resources that are no longer in Git
      selfHeal: true     # Automatically sync when cluster state drifts from Git
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Ignore replica count changes (for HPA)


# Test workflow run